### PR TITLE
fix: add passHref prop to next/link when using a custom anchor tag

### PR DESCRIPTION
**Pull request by mcansh**
without this, the anchor tag in the dom wont have an href.

ref: https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag

Signed-off-by: Logan McAnsh <logan@mcan.sh>

### CODE REVIEW

**Comment by brianlovin** [comment]
Looks like Prettier went a little wild here, and we might have different settings (or mine might not even be working). Would you be up for updating this PR to only include the `passHref` changes? Thank you!

**Comment by mcansh** [comment]
you got it

**Comment by brianlovin** [comment]
Really appreciate this fix, thanks @mcansh 🙏

**Comment by mcansh** [comment]
no problem at all 👍, there's a couple links that could also be converted to use next/link, if you want those updated, I can update them too 😄.

**Comment by brianlovin** [comment]
Oh, if you spotted opportunities where I missed them, that'd be great to have!

**Comment by mcansh** [comment]
lol maybe I'm going crazy, but I can't find them now 🤪

**Pull request merged**
